name: Build and Release

on:
  push:
    branches:
      - main  # ou la branche de votre choixce

jobs:
  build:
    name: Build on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.11  # Utilisation de Python 3.11

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt  # utilisez votre fichier requirements.txt
        pip install pyinstaller  # and any other dependencies

    - name: Build with PyInstaller
      run: |
        pyinstaller main.spec

    - name: Upload Artifacts
      uses: actions/upload-artifact@v2
      with:
        name: ${{ matrix.os }}-binary
        path: dist/*
